name: Test artifact in github

on: push

jobs:

    job_1:
        name: Upload Artifact
        runs-on: ubuntu-latest
        steps:
            - name: "Create a local file"
              run: echo "Hey this is just to test how artifacts work!"

            - uses: actions/upload-artifact@v2
              with:
                name: file
                path: file.txt

    job_2:
        name: Download Artifact
        runs-on: ubuntu-latest
        needs: job_1
        steps:
            - uses: actions/download-artifact@v2
              with:
                name: file
            - run: cat file.txt    #prints the content in the filenamed file.txt

