name: The basic workflow

#controls when the workflow will run
on:
#triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#A workfliw consistes of jobs, that can run sequentially or in parallel
jobs:

  #This workflow has a job called "build"
  build:

    #The type of runner where the job will run on
    runs-on: ubuntu-latest

    #Sequence of tasks that will execute as part of the job
    steps:
      #Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

      #Runs a single command using runners shell
    - name: Run a one line script
      run: echo Hello, World
      
      #Runs a set of commands using runners shell
    - name: Run multi line script
      run: 
        echo Add other actions to build,
        echo test, and deploy your project

  build-api:
    runs-on: windows-latest
    steps:
    - run: echo "Building API"

  build-db:
    needs: build
    runs-on: windows-latest
    steps:
    - run: echo "Hello Windows"

  package:
    needs: [build,build-db]
    runs-on: macos-latest
    steps:
    - run: echo "Hello MacOS"
