name: List of all variables

on:
    workflow_dispatch: 

jobs:
    ubuntu_environment_variables:
        runs-on: ubuntu-latest
        steps:
            - run: env
    windows_environment_variables:
        runs-on: windows-latest
        steps:
            - run: env
    MacOS_environment_variables:
        runs-on: macos-latest
        steps:
            - run: env
    job1:
        runs-on: ubuntu-latest

        outputs:
            output1: ${{ steps.step1.outputs.test}}
            output2: ${{ steps.step2.outputs.test}}
        
        steps:
            - id: step1
              run: echo "set-output name=test::value1"  #"set-output" this is necessary, it sets the output
            - id: step2
              run: echo "set-output name=test::value2"  
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - run: |                                #use '|' for multi line
                echo "Print"
                echo output1: ${{needs.job1.outputs.output1}}
                echo output2: ${{needs.job1.outputs.output2}}

