name: List of all variables

on:
    workflow_dispatch: 

jobs:
    # ubuntu_environment_variables:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - run: env
    # windows_environment_variables:
    #     runs-on: windows-latest
    #     steps:
    #         - run: env
    # MacOS_environment_variables:
    #     runs-on: macos-latest
    #     steps:
    #         - run: env
    job1:
        runs-on: ubuntu-latest
        outputs:
            out1: ${{ steps.step1.outputs.test1 }}
            out2: ${{ steps.step2.outputs.test2 }}
        steps:
            - id: step1
              run: echo "::set-output name=test1::value1"
            - id: step2
              run: echo "::set-output name=test2::value2"

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - run: |                                # use '|' for multi-line
                echo "Print"
                echo "out1: ${{ needs.job1.outputs.out1 }}"
                echo "out2: ${{ needs.job1.outputs.out2 }}"
